@id = d0b3bfe3-f5fa-40cb-a10e-5fc72fc62b8c
PUT http://localhost:5272/Store/{{id}}
Content-Type: application/json

{
    "name": "Home Office Furniture Upsert",
    "description": "Furniture optimized for productivity and comfort in home offices, including desks, office chairs, filing cabinets, bookshelves, and ergonomic accessories",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "companies": [
        "Mandaue Foam",
        "Dimensione",
        "Home Factory Outlets",
        "Bambu Furniture",
        "Furniture Republic",
        "Metro Furniture",
        "Cebu Home and Builders Centre (CHBC)",
        "Designs Ligna",
        "Our Home"
    ],
     "furnitures": [
        "Sofa",
        "Armchair",
        "Dining table",
        "Dining chairs",
        "Coffee table",
        "Side table",
        "Bed frame",
        "Mattress",
        "Wardrobe",
        "Dresser",
        "Nightstand",
        "Bookshelf",
        "Desk",
        "Office chair",
        "TV stand",
        "Ottoman",
        "Pouf",
        "Bench",
        "Console table",
        "Bar stool"
  ]
}
